# Generated by Django 3.2.5 on 2021-11-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('info', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
