# Generated by Django 3.2.5 on 2021-12-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_costumer_sales_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='email',
            field=models.CharField(max_length=256),
        ),
    ]
