# Generated by Django 3.2.9 on 2021-12-29 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webApp', '0003_alter_costumer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_box', models.CharField(max_length=256)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
