# Generated by Django 3.2.9 on 2021-12-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_alter_costumer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=256)),
                ('message_box', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
