# Generated by Django 3.2.9 on 2021-12-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0005_rename_user_id_userchatmessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchatmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='userchatmessage',
            name='user_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='userchatmessage',
            name='message_box',
            field=models.CharField(default='', max_length=256),
        ),
    ]
